trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo flucxd!
  displayName: 'Run a one-line script'

# Install Kubectl
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

# Install Helm version3
- task: HelmInstaller@0
  inputs:
    helmVersion: 'latest'
    installKubectl: true

# Install Azure Cli
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource-manager-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group Kubernetes_dev --name K8stest_dev
      helm repo add fluxcd https://charts.fluxcd.io
      kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml

